---
- name: This playbook sets up NZ iNaturalist WFS infrastructure with Vagrant
  hosts: vagrant
  sudo: true
  sudo_user: root

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - postgresql
    - nginx
    - mapserver
